const SEED_MENU_CATEGORIES = [
  ['refreshers', 'Refreshers', 'Fruit-forward iced energy and tea refreshers', 10],
  ['add-ons', 'Add Ons', 'Optional extras and boosts available at the counter', 20],
  ['flavors', 'Flavors', 'Free syrup and fruit flavor options for pickup drinks', 25],
  ['lattes', 'Lattes', 'Espresso and milk in small, medium, and large pours', 30],
  ['roadrunner', 'Roadrunner', 'House specialty drinks with an extra charge of energy', 40],
  ['chai', 'Chai', 'Spiced chai drinks across the full size run', 50],
  ['lemonades', 'Lemonades', 'Bright citrus drinks for an all-day lift', 60],
  ['teas', 'Teas', 'Hot tea pours and comforting cafe staples', 70],
  ['matcha', 'Matcha', 'Matcha-based drinks with layered sweetness', 80],
  ['reg-coffee', 'Reg Coffee', 'Daily coffee service with classic sizing', 90],
  ['milk-options', 'Milk Options', 'Alternative milk upgrades and substitutions', 100],
  ['cake-pops', 'Cake Pops', 'Sweet grab-and-go bakery treats', 110],
  ['uncategorized', 'Other', 'House specialties, Italian sodas, and featured extras.', 120],
];

const SEED_MENU_ITEMS = [
  ['refreshers', 'Small Refresher', 'A small fruit-forward refresher served iced with a bright, energizing finish.', 3, 1, 10, 'X23QRTBMCGR92'],
  ['refreshers', 'Medium Refresher', 'A medium fruit-forward refresher served iced with a bright, energizing finish.', 4, 1, 20, 'ZBDE085D75764'],
  ['refreshers', 'Large Refresher', 'A large fruit-forward refresher served iced with a bright, energizing finish.', 5, 1, 30, 'WYB56XADXY9HY'],
  ['add-ons', 'Redbull', 'Add a Red Bull boost for more energy in the cup.', 2, 1, 10, 'HB11D2VN8XZWA'],
  ['add-ons', 'Lotus', 'Add Lotus energy for a brighter, fruit-forward lift.', 2, 1, 20, '20XTCPXMJBREA'],
  ['add-ons', 'Boba', 'Add boba pearls for extra texture and sweetness.', 1, 1, 30, 'TNTYENBSAWKT0'],
  ['add-ons', 'Cream/whip', 'Finish the drink with cream or whip for added richness.', 1, 1, 40, '39QF35J5WEZGT'],
  ['add-ons', 'Make It Dirty', 'Make it dirty with an added espresso-style coffee edge.', 1, 1, 50, '9T2KK4CRV3VY0'],
  ['add-ons', 'Coldfoam', 'Top the drink with cold foam for a richer finish.', 1, 1, 60, 'CFV68S3A2ZQ8M'],
  ['add-ons', 'Fog', 'Add Fog to customize the drink for pickup.', 1, 1, 70, '07XNFD9XCT1M4'],
  ['add-ons', 'Espresso', 'Add an extra espresso shot for a stronger coffee kick.', 2, 1, 80, 'QCPVB329N37N8'],
  ['add-ons', 'Egg Nog', 'Add Egg Nog to customize the drink for pickup.', 2, 1, 90, 'TZWJRXS38ZEXJ'],
  ['flavors', 'Amaretto', 'Free flavor option for pickup drinks.', 0, 1, 10, null],
  ['flavors', 'Almond', 'Free flavor option for pickup drinks.', 0, 1, 20, null],
  ['flavors', 'Banana', 'Free flavor option for pickup drinks.', 0, 1, 30, null],
  ['flavors', 'Blackberry', 'Free flavor option for pickup drinks.', 0, 1, 40, null],
  ['flavors', 'Blue Raspberry', 'Free flavor option for pickup drinks.', 0, 1, 50, null],
  ['flavors', 'Blueberry', 'Free flavor option for pickup drinks.', 0, 1, 60, null],
  ['flavors', 'Butter Pecan', 'Free flavor option for pickup drinks.', 0, 1, 70, null],
  ['flavors', 'Cherry', 'Free flavor option for pickup drinks.', 0, 1, 80, null],
  ['flavors', 'Coconut', 'Free flavor option for pickup drinks.', 0, 1, 90, null],
  ['flavors', 'Dragonfruit', 'Free flavor option for pickup drinks.', 0, 1, 100, null],
  ['flavors', 'Gingerbread', 'Free flavor option for pickup drinks.', 0, 1, 110, null],
  ['flavors', 'Green Apple', 'Free flavor option for pickup drinks.', 0, 1, 120, null],
  ['flavors', 'Hazelnut', 'Free flavor option for pickup drinks.', 0, 1, 130, null],
  ['flavors', 'Honey', 'Free flavor option for pickup drinks.', 0, 1, 140, null],
  ['flavors', 'Irish Cream', 'Free flavor option for pickup drinks.', 0, 1, 150, null],
  ['flavors', 'Kiwi', 'Free flavor option for pickup drinks.', 0, 1, 160, null],
  ['flavors', 'Lavender', 'Free flavor option for pickup drinks.', 0, 1, 170, null],
  ['flavors', 'Lemon', 'Free flavor option for pickup drinks.', 0, 1, 180, null],
  ['flavors', 'Lime', 'Free flavor option for pickup drinks.', 0, 1, 190, null],
  ['flavors', 'Macadamia Nut', 'Free flavor option for pickup drinks.', 0, 1, 200, null],
  ['flavors', 'Mango', 'Free flavor option for pickup drinks.', 0, 1, 210, null],
  ['flavors', 'Orange', 'Free flavor option for pickup drinks.', 0, 1, 220, null],
  ['flavors', 'Passion Fruit', 'Free flavor option for pickup drinks.', 0, 1, 230, null],
  ['flavors', 'Peach', 'Free flavor option for pickup drinks.', 0, 1, 240, null],
  ['flavors', 'Peanut Butter', 'Free flavor option for pickup drinks.', 0, 1, 250, null],
  ['flavors', 'Peppermint', 'Free flavor option for pickup drinks.', 0, 1, 260, null],
  ['flavors', 'Pineapple', 'Free flavor option for pickup drinks.', 0, 1, 270, null],
  ['flavors', 'Pistachio', 'Free flavor option for pickup drinks.', 0, 1, 280, null],
  ['flavors', 'Pomegranate', 'Free flavor option for pickup drinks.', 0, 1, 290, null],
  ['flavors', 'Pumpkin Spice', 'Free flavor option for pickup drinks.', 0, 1, 300, null],
  ['flavors', 'Raspberry', 'Free flavor option for pickup drinks.', 0, 1, 310, null],
  ['flavors', 'Strawberry', 'Free flavor option for pickup drinks.', 0, 1, 320, null],
  ['flavors', 'Toasted Marshmallow', 'Free flavor option for pickup drinks.', 0, 1, 330, null],
  ['flavors', 'Toffee Nut', 'Free flavor option for pickup drinks.', 0, 1, 340, null],
  ['flavors', 'Vanilla', 'Free flavor option for pickup drinks.', 0, 1, 350, null],
  ['flavors', 'Watermelon', 'Free flavor option for pickup drinks.', 0, 1, 360, null],
  ['lattes', 'Small Latte', 'A small espresso latte with steamed milk and a smooth cafe finish.', 4, 1, 10, 'CQT0S2056JEG8'],
  ['lattes', 'Medium Latte', 'A medium espresso latte with steamed milk and a smooth cafe finish.', 5, 1, 20, 'EJ6NEYZ4C3M5T'],
  ['lattes', 'Large Latte', 'A large espresso latte with steamed milk and a smooth cafe finish.', 6, 1, 30, '4QZ493YWX2DBC'],
  ['roadrunner', 'Small Roadrunner', "A small Roadrunner specialty drink with Java Drip Coffee's extra-charge energy profile.", 5, 1, 10, 'PB59X26MVS3ZJ'],
  ['roadrunner', 'Medium Roadrunner', "A medium Roadrunner specialty drink with Java Drip Coffee's extra-charge energy profile.", 6, 1, 20, 'NQKGMFDDMBMEJ'],
  ['roadrunner', 'Large Roadrunner', "A large Roadrunner specialty drink with Java Drip Coffee's extra-charge energy profile.", 7, 1, 30, 'WF0YR5SH53Z3J'],
  ['chai', 'Small Chai', 'A small spiced chai drink with warming flavor and a smooth finish.', 4, 1, 10, '6PAV71E68QBF2'],
  ['chai', 'Medium Chai', 'A medium spiced chai drink with warming flavor and a smooth finish.', 5, 1, 20, '2WXQZF8QN254T'],
  ['chai', 'Large Chai', 'A large spiced chai drink with warming flavor and a smooth finish.', 6, 1, 30, 'ETB01K93EB4T4'],
  ['lemonades', 'Small Lemonade', 'A small citrus-forward lemonade built for a crisp all-day lift.', 4, 1, 10, '1YJWEEWRQ0RYJ'],
  ['lemonades', 'Medium Lemonade', 'A medium citrus-forward lemonade built for a crisp all-day lift.', 5, 1, 20, 'G3WKD2YHMTF4E'],
  ['lemonades', 'Large Lemonade', 'A large citrus-forward lemonade built for a crisp all-day lift.', 6, 1, 30, '54DDD8H2QPZSM'],
  ['teas', 'Small Tea', 'A small tea pour prepared for a simple, comforting cafe break.', 3, 1, 10, 'R1ABAS1CMCE6R'],
  ['teas', 'Medium Tea', 'A medium tea pour prepared for a simple, comforting cafe break.', 4, 1, 20, 'SNMDRNV15SK04'],
  ['teas', 'Large Tea', 'A large tea pour prepared for a simple, comforting cafe break.', 5, 1, 30, 'RDGPV7H9N3Z1R'],
  ['matcha', 'Small Matcha', 'A small matcha drink with layered sweetness and an earthy finish.', 5, 1, 10, '4N7CBSQB5SJWW'],
  ['matcha', 'Medium Matcha', 'A medium matcha drink with layered sweetness and an earthy finish.', 6, 1, 20, 'TWP3APY6Y74GG'],
  ['matcha', 'Large Matcha', 'A large matcha drink with layered sweetness and an earthy finish.', 7, 1, 30, '0RFSF4AFKAM94'],
  ['reg-coffee', 'Small Coffee', 'A small house coffee poured fresh for the daily Gallup routine.', 3, 1, 10, 'GSQP0G0Y4K6D4'],
  ['reg-coffee', 'Medium Coffee', 'A medium house coffee poured fresh for the daily Gallup routine.', 4, 1, 20, 'J0XH7Z5H0K0ZJ'],
  ['reg-coffee', 'Large Coffee', 'A large house coffee poured fresh for the daily Gallup routine.', 5, 1, 30, 'DCV8PJMXR3B70'],
  ['milk-options', 'Oat Milk', 'Oat Milk is available as an alternative milk upgrade for pickup drinks.', 2, 1, 10, 'EXKFYH3G09D3T'],
  ['milk-options', 'Almond Milk', 'Almond Milk is available as an alternative milk upgrade for pickup drinks.', 1, 1, 20, 'MNJYMDEJ8SD58'],
  ['milk-options', 'Coconut Milk', 'Coconut Milk is available as an alternative milk upgrade for pickup drinks.', 2, 1, 30, 'A76S7NVSQX388'],
  ['cake-pops', 'Cake Pop', 'A sweet grab-and-go cake pop for a quick coffee pairing.', 3, 1, 10, 'D0DXWYDD1V7AP'],
  ['uncategorized', 'Small Italian', 'A small Italian soda with bright flavor and a crisp sparkling finish.', 3, 1, 10, 'M88R0E93A2B9C'],
  ['uncategorized', 'Medium Italian', 'A medium Italian soda with bright flavor and a crisp sparkling finish.', 4, 1, 20, 'THD9KGGAX91JR'],
  ['uncategorized', 'Large Italian', 'A large Italian soda with bright flavor and a crisp sparkling finish.', 5, 1, 30, 'CRH1BQRAY553T'],
  ['uncategorized', 'Small Fog', 'A small London fog-style drink with tea, sweetness, and a smooth milk finish.', 4, 1, 40, 'Z7HCP27AT9VK6'],
  ['uncategorized', 'Medium Fog', 'A medium London fog-style drink with tea, sweetness, and a smooth milk finish.', 5, 1, 50, 'CJPCWK7KHXHQ8'],
  ['uncategorized', 'Large Fog', 'A large London fog-style drink with tea, sweetness, and a smooth milk finish.', 6, 1, 60, 'CRJFFJX1ADFXC'],
];

module.exports = {
  SEED_MENU_CATEGORIES,
  SEED_MENU_ITEMS,
};
